url: "https://ganand01.github.io/DSC180A-Methodology-5/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 