

title: Gita Anand Methodology 5 Assignment
email: gianand@ucsd.edu
url: "https://ganand01.github.io/DSC180A-Methodology-5/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
